/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/availability/available/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get available ministers for a specific date and service */
    get: operations['v1_availability_available_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/availability/calendar/{slug}/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a minister's availability calendar for a specific month */
    get: operations['v1_availability_calendar_retrieve'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/availability/ministers/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all active ministers */
    get: operations['v1_availability_ministers_list'];
    put?: never;
    /** Create a new minister profile */
    post: operations['v1_availability_ministers_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/availability/ministers/{slug}/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get minister details */
    get: operations['v1_availability_ministers_retrieve'];
    /** Update minister details */
    put: operations['v1_availability_ministers_update'];
    post?: never;
    /** Delete minister profile */
    delete: operations['v1_availability_ministers_destroy'];
    options?: never;
    head?: never;
    /** Partially update minister details */
    patch: operations['v1_availability_ministers_partial_update'];
    trace?: never;
  };
  '/api/v1/availability/ministers/{slug}/available/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get available slots for a minister on a specific date */
    get: operations['v1_availability_ministers_available_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/availability/ministers/{slug}/weekly/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get minister weekly availability */
    get: operations['v1_availability_ministers_weekly_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/availability/parishes/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all active parishes */
    get: operations['v1_availability_parishes_list'];
    put?: never;
    /** Create a new parish */
    post: operations['v1_availability_parishes_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/availability/parishes/{slug}/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get parish details */
    get: operations['v1_availability_parishes_retrieve'];
    /** Update parish details */
    put: operations['v1_availability_parishes_update'];
    post?: never;
    /** Delete parish */
    delete: operations['v1_availability_parishes_destroy'];
    options?: never;
    head?: never;
    /** Partially update parish details */
    patch: operations['v1_availability_parishes_partial_update'];
    trace?: never;
  };
  '/api/v1/availability/services/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all active service types */
    get: operations['v1_availability_services_list'];
    put?: never;
    /** Create a new service type */
    post: operations['v1_availability_services_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/availability/services/{slug}/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get service type details */
    get: operations['v1_availability_services_retrieve'];
    /** Update service type */
    put: operations['v1_availability_services_update'];
    post?: never;
    /** Delete service type */
    delete: operations['v1_availability_services_destroy'];
    options?: never;
    head?: never;
    /** Partially update service type */
    patch: operations['v1_availability_services_partial_update'];
    trace?: never;
  };
  '/api/v1/bible/books/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List all books with optional testament filter and name search
     * @description Returns paginated list of all books, optionally filtered by testament and searched by name.
     */
    get: operations['v1_bible_books_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/bible/books/{book_id}/chapters/{chapter_number}/verses/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List verses for a specific chapter
     * @description Returns list of verses for a specific chapter.
     */
    get: operations['v1_bible_books_chapters_verses_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/bible/search/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Lexical and hybrid search across all verses
     * @description Search endpoint using lexical/hybrid search.
     */
    get: operations['v1_bible_search_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/bible/testaments/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List testaments with nested books
     * @description Returns the lists of testaments (Ancien & Nouveau) with nested books.
     */
    get: operations['v1_bible_testaments_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/bible/testaments/{testament_slug}/books/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List all books for a specific testament
     * @description Returns all books for a given testament.
     */
    get: operations['v1_bible_testaments_books_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/errors/trigger/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['v1_errors_trigger_retrieve'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/errors/trigger/exception/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['v1_errors_trigger_exception_retrieve'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/errors/trigger/unique/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['v1_errors_trigger_unique_retrieve'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/files/upload/direct/finish/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['v1_files_upload_direct_finish_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/files/upload/direct/local/{file_id}/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['v1_files_upload_direct_local_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/files/upload/direct/start/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['v1_files_upload_direct_start_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/files/upload/standard/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['v1_files_upload_standard_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/liturgy/date/{date_str}/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Liturgical data for a specific date
     * @description Retrieve the liturgical texts for a specific date (YYYY-MM-DD).
     *             If the data is not available locally, this endpoint returns a 404.
     */
    get: operations['v1_liturgy_date_retrieve'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/liturgy/offices/{id}/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get details of a specific Office (e.g., Lauds)
     * @description Retrieve a specific Office by its ID.
     *             Returns the hymns, psalms, and intercessions associated with that office.
     */
    get: operations['v1_liturgy_offices_retrieve'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/liturgy/readings/{id}/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get details of a specific Mass Reading
     * @description Retrieve a specific Reading (e.g., the Gospel) by its ID.
     *             This includes any matched local Bible verses (cross-references).
     */
    get: operations['v1_liturgy_readings_retrieve'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/liturgy/today/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get today's Liturgical data (Mass Readings, Offices)
     * @description Retrieve the official liturgical texts for the CURRENT day (in the 'romain' zone).
     *             This includes the 'Mass' readings (First Reading, Gospel, etc.) and the
     *             Liturgy of the Hours text blocks (Lauds, Vespers, Compline, etc.).
     */
    get: operations['v1_liturgy_today_retrieve'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/rag/query/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Ask a question to the AI assistant using RAG (Retrieval-Augmented Generation) */
    post: operations['v1_rag_query_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/rosary/day/{day}/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get rosary prayers for a specific day of the week
     * @description Fetches the Rosary Group assigned to a given weekday, along with the introductory
     *             and concluding standalone prayers.
     *
     *             **Day mapping (0-6):**
     *             0: Monday (Joyeux)
     *             1: Tuesday (Douloureux)
     *             2: Wednesday (Glorieux)
     *             3: Thursday (Lumineux)
     *             4: Friday (Douloureux)
     *             5: Saturday (Joyeux)
     *             6: Sunday (Glorieux)
     */
    get: operations['v1_rosary_day_retrieve'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/rosary/groups/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List all rosary groups (Mysteries)
     * @description Returns a list of all Rosary Groups (Joyeux, Lumineux, Douloureux, Glorieux).
     *
     *             **What is a Rosary Group?**
     *             In the Catholic tradition, the Rosary is a meditative prayer based on the life of Jesus Christ.
     *             It is divided into 4 groups called 'Mysteries'. Each group contains 5 specific events
     *             (e.g., 'The Annunciation' is the 1st Joyful Mystery).
     */
    get: operations['v1_rosary_groups_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/rosary/groups/{slug}/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get details of a specific rosary group by slug
     * @description Retrieve a specific Rosary Group (e.g., 'joyeux') and its 5 mysteries.
     *
     *             **Structure of a Mystery (Dizaine/Decade):**
     *             When praying a mystery, the believer meditates on the event (often reading a short scripture),
     *             then recites a specific sequence of prayers:
     *             1. One 'Our Father' (Notre Père)
     *             2. Ten 'Hail Mary's (Je vous salue Marie) - This is why it's called a 'decade' or 'dizaine'.
     *             3. One 'Glory Be' (Gloire au Père)
     *             4. (Optional) The Fatima Prayer
     *
     *             The API returns this exact sequential order of prayers under each mystery.
     */
    get: operations['v1_rosary_groups_retrieve'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/rosary/mysteries/{id}/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get details of a specific Mystery (Dizaine)
     * @description Retrieve a specific Mystery by its ID, complete with its scriptural meditation
     *             and the full sequence of prayers (1 Our Father, 10 Hail Marys, etc.) that
     *             compose its 'decade'.
     */
    get: operations['v1_rosary_mysteries_retrieve'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/rosary/prayers/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List all foundational standalone prayers
     * @description Retrieve all foundational pieces used in the Rosary, such as the 'Our Father',
     *             the 'Apostles Creed' (Je crois en Dieu), or the 'Fatima Prayer'.
     */
    get: operations['v1_rosary_prayers_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/rosary/search/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Search within rosary prayers using text match */
    get: operations['v1_rosary_search_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/rosary/today/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get today's rosary prayers along with standalone prayers
     * @description Fetches the Rosary Group assigned to the current day of the week, along with the introductory
     *             and concluding prayers.
     *
     *             **Daily Tradition:**
     *             - Monday & Saturday: Joyful Mysteries (Joyeux)
     *             - Tuesday & Friday: Sorrowful Mysteries (Douloureux)
     *             - Wednesday & Sunday: Glorious Mysteries (Glorieux)
     *             - Thursday: Luminous Mysteries (Lumineux)
     *
     *             This endpoint also returns `standalone_prayers` (like the Apostles' Creed or the Hail Holy Queen)
     *             which are recited at the very beginning and very end of the entire Rosary.
     */
    get: operations['v1_rosary_today_retrieve'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/rosary/vector_search/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Search within rosary prayers using vector embeddings
     * @description Stub endpoint for future RAG implementation via pgvector.
     */
    get: operations['v1_rosary_vector_search_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/users/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['v1_users_retrieve'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/users/{user_id}/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['v1_users_retrieve_2'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/users/{user_id}/update/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['v1_users_update_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/users/create/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['v1_users_create_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @description Serializer for external AELF resources (audio/youtube). */
    AelfResource: {
      /** Format: uri */
      audio_url?: string | null;
      /** Format: uri */
      youtube_url?: string | null;
    };
    BookMetadataOutput: {
      readonly id: number;
      name: string;
      slug: string;
      order: number;
      readonly testament: string;
      verse_count?: number;
      readonly chapter_count: number;
    };
    Group: {
      readonly id: number;
      name: string;
      slug: string;
      /** Format: uri */
      readonly audio_file: string;
      readonly mysteries: string;
    };
    /**
     * @description Main serializer aggregating all data for a specific liturgical date.
     *     Includes nested resources, readings, and offices if prefetched.
     */
    LiturgicalDate: {
      readonly id: number;
      /** Format: date */
      date: string;
      zone: string;
      day_name?: string;
      season?: string;
      mystery?: string;
      notes?: string;
      readonly resource: components['schemas']['AelfResource'];
      readonly readings: string;
      readonly offices: string;
    };
    MinisterDetail: {
      readonly id: number;
      first_name: string;
      last_name: string;
      readonly slug: string;
      /** Format: uri */
      photo?: string | null;
      role?: components['schemas']['RoleEnum'];
      readonly role_display: string;
      readonly parish: components['schemas']['Parish'];
      parish_id: number;
      user_id?: number | null;
      bio?: string;
      is_active?: boolean;
      readonly weekly_availabilities: string;
    };
    MinisterList: {
      readonly id: number;
      first_name: string;
      last_name: string;
      readonly slug: string;
      /** Format: uri */
      photo?: string | null;
      role?: components['schemas']['RoleEnum'];
      readonly role_display: string;
      readonly parish: components['schemas']['Parish'];
      parish_id: number;
      user_id?: number | null;
      is_active?: boolean;
    };
    MonthCalendar: {
      available_days: string[];
      full_days: string[];
      partial_days: string[];
    };
    Mystery: {
      readonly id: number;
      order: number;
      title: string;
      /** @description Scripture reading or meditation for the mystery */
      meditation?: string | null;
      /** Format: uri */
      readonly audio_file: string;
      /** @description Duration in seconds */
      audio_duration?: number | null;
      readonly prayers: string;
    };
    /** @description Serializer for Liturgy of the Hours texts. */
    Office: {
      readonly id: number;
      office_type: string;
      /** @description Hymn text */
      hymn?: string;
      /** @description List of psalms/canticles objects */
      psalms?: unknown;
      /** @description Main canticle (Benedictus/Magnificat/Nunc Dimittis) */
      canticle?: string;
      /** @description Short readings and responsories */
      readings?: unknown;
      /** @description Intercessions text */
      intercessions?: string;
      /** @description Any additional unmodified data */
      raw_metadata?: unknown;
    };
    PaginatedMinisterListList: {
      /** @example 123 */
      count: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=400&limit=100
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=200&limit=100
       */
      previous?: string | null;
      results: components['schemas']['MinisterList'][];
    };
    PaginatedParishList: {
      /** @example 123 */
      count: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=400&limit=100
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=200&limit=100
       */
      previous?: string | null;
      results: components['schemas']['Parish'][];
    };
    PaginatedServiceTypeList: {
      /** @example 123 */
      count: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=400&limit=100
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=200&limit=100
       */
      previous?: string | null;
      results: components['schemas']['ServiceType'][];
    };
    PaginatedWeeklyAvailabilityList: {
      /** @example 123 */
      count: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=400&limit=100
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=200&limit=100
       */
      previous?: string | null;
      results: components['schemas']['WeeklyAvailability'][];
    };
    Parish: {
      readonly id: number;
      name: string;
      readonly slug: string;
      address?: string;
      city: string;
      country?: string;
      /** Format: decimal */
      latitude?: string | null;
      /** Format: decimal */
      longitude?: string | null;
      is_active?: boolean;
    };
    PatchedMinisterDetail: {
      readonly id?: number;
      first_name?: string;
      last_name?: string;
      readonly slug?: string;
      /** Format: uri */
      photo?: string | null;
      role?: components['schemas']['RoleEnum'];
      readonly role_display?: string;
      readonly parish?: components['schemas']['Parish'];
      parish_id?: number;
      user_id?: number | null;
      bio?: string;
      is_active?: boolean;
      readonly weekly_availabilities?: string;
    };
    PatchedParish: {
      readonly id?: number;
      name?: string;
      readonly slug?: string;
      address?: string;
      city?: string;
      country?: string;
      /** Format: decimal */
      latitude?: string | null;
      /** Format: decimal */
      longitude?: string | null;
      is_active?: boolean;
    };
    PatchedServiceType: {
      readonly id?: number;
      name?: string;
      readonly slug?: string;
      description?: string;
      duration_minutes?: number;
    };
    Prayer: {
      readonly id: number;
      type: components['schemas']['TypeEnum'];
      readonly type_display: string;
      language?: string;
      text: string;
    };
    RagQuery: {
      /** @description The question or prompt to ask the assistant (e.g., 'Quel mystère aujourd'hui et as-tu un prêtre dispo à Mbour ?') */
      query: string;
    };
    RagResponse: {
      /** @description The generated response from the LLM. */
      answer: string;
      /** @description The raw context retrieved from the database. */
      context: string;
      /** @description The metadata showing how the LLM routed the question. */
      intent: {
        [key: string]: unknown;
      };
    };
    /** @description Serializer for Mass readings. */
    Reading: {
      readonly id: number;
      type: string;
      citation?: string;
      text: string;
      raw_metadata?: unknown;
      readonly matched_verses: components['schemas']['VerseOutput'][];
    };
    /**
     * @description * `PRIEST` - Priest
     *     * `SISTER` - Sister
     *     * `DEACON` - Deacon
     *     * `RELIGIOUS` - Religious
     *     * `BISHOP` - Bishop
     * @enum {string}
     */
    RoleEnum: 'PRIEST' | 'SISTER' | 'DEACON' | 'RELIGIOUS' | 'BISHOP';
    RosaryDay: {
      readonly id: number;
      weekday: components['schemas']['WeekdayEnum'];
      readonly weekday_display: string;
      readonly group: components['schemas']['Group'];
    };
    /** @description Shape of search results grouped by book. */
    SearchBookGroupOutput: {
      book: components['schemas']['SearchBookMetadataOutput'];
      matches: components['schemas']['SearchMatchOutput'][];
    };
    /** @description Shape of book metadata returned by search service. */
    SearchBookMetadataOutput: {
      id: number;
      name: string;
      slug: string;
      order: number;
      testament: string;
    };
    /** @description Shape of the search result specific to a matching verse. */
    SearchMatchOutput: {
      verse: components['schemas']['SearchVerseOutput'];
      /** @default false */
      no_internal_source: boolean;
      /** Format: double */
      score?: number;
    };
    /** @description Extends PrayerSerializer to show rank from full text search. */
    SearchPrayer: {
      readonly id: number;
      type: components['schemas']['TypeEnum'];
      readonly type_display: string;
      language?: string;
      text: string;
      /** Format: double */
      readonly rank: number;
    };
    SearchVerseOutput: {
      id: number;
      number: number;
      chapter: {
        [key: string]: unknown;
      };
      text: string;
    };
    ServiceType: {
      readonly id: number;
      name: string;
      readonly slug: string;
      description?: string;
      duration_minutes?: number;
    };
    Slot: {
      /** Format: time */
      start: string;
      /** Format: time */
      end: string;
      service: string;
      service_name: string;
    };
    TestamentWithBooksOutput: {
      slug: string;
      name: string;
      order?: number;
      readonly books: {
        [key: string]: unknown;
      }[];
    };
    TodayRosaryOutput: {
      day: components['schemas']['RosaryDay'];
      standalone_prayers: components['schemas']['Prayer'][];
    };
    /**
     * @description * `SIGN_OF_CROSS` - Sign of Cross
     *     * `CREED` - Apostles Creed
     *     * `OUR_FATHER` - Our Father
     *     * `HAIL_MARY` - Hail Mary
     *     * `GLORY_BE` - Glory Be
     *     * `FATIMA` - Fatima Prayer
     *     * `HOLY_QUEEN` - Hail Holy Queen
     *     * `FINAL_PRAYER` - Final Prayer
     *     * `OTHER` - Other
     * @enum {string}
     */
    TypeEnum:
      | 'SIGN_OF_CROSS'
      | 'CREED'
      | 'OUR_FATHER'
      | 'HAIL_MARY'
      | 'GLORY_BE'
      | 'FATIMA'
      | 'HOLY_QUEEN'
      | 'FINAL_PRAYER'
      | 'OTHER';
    VerseOutput: {
      readonly id: number;
      number: number;
      text: string;
    };
    /**
     * @description * `0` - Monday
     *     * `1` - Tuesday
     *     * `2` - Wednesday
     *     * `3` - Thursday
     *     * `4` - Friday
     *     * `5` - Saturday
     *     * `6` - Sunday
     * @enum {integer}
     */
    WeekdayEnum: 0 | 1 | 2 | 3 | 4 | 5 | 6;
    WeeklyAvailability: {
      readonly id: number;
      weekday: components['schemas']['WeekdayEnum'];
      readonly weekday_display: string;
      /** Format: time */
      start_time: string;
      /** Format: time */
      end_time: string;
      readonly service_type: components['schemas']['ServiceType'];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  v1_availability_available_list: {
    parameters: {
      query: {
        date: string;
        service: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MinisterList'][];
        };
      };
    };
  };
  v1_availability_calendar_retrieve: {
    parameters: {
      query: {
        month: string;
      };
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MonthCalendar'];
        };
      };
    };
  };
  v1_availability_ministers_list: {
    parameters: {
      query?: {
        is_active?: boolean;
        /** @description Number of results to return per page. */
        limit?: number;
        /** @description The initial index from which to return the results. */
        offset?: number;
        parish__slug?: string;
        /**
         * @description * `PRIEST` - Priest
         *     * `SISTER` - Sister
         *     * `DEACON` - Deacon
         *     * `RELIGIOUS` - Religious
         *     * `BISHOP` - Bishop
         */
        role?: 'BISHOP' | 'DEACON' | 'PRIEST' | 'RELIGIOUS' | 'SISTER';
        /** @description A search term. */
        search?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaginatedMinisterListList'];
        };
      };
    };
  };
  v1_availability_ministers_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MinisterList'];
        'multipart/form-data': components['schemas']['MinisterList'];
        'application/x-www-form-urlencoded': components['schemas']['MinisterList'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MinisterList'];
        };
      };
    };
  };
  v1_availability_ministers_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MinisterDetail'];
        };
      };
    };
  };
  v1_availability_ministers_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MinisterDetail'];
        'multipart/form-data': components['schemas']['MinisterDetail'];
        'application/x-www-form-urlencoded': components['schemas']['MinisterDetail'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MinisterDetail'];
        };
      };
    };
  };
  v1_availability_ministers_destroy: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  v1_availability_ministers_partial_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['PatchedMinisterDetail'];
        'multipart/form-data': components['schemas']['PatchedMinisterDetail'];
        'application/x-www-form-urlencoded': components['schemas']['PatchedMinisterDetail'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MinisterDetail'];
        };
      };
    };
  };
  v1_availability_ministers_available_list: {
    parameters: {
      query: {
        date: string;
      };
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Slot'][];
        };
      };
    };
  };
  v1_availability_ministers_weekly_list: {
    parameters: {
      query?: {
        /** @description Number of results to return per page. */
        limit?: number;
        /** @description The initial index from which to return the results. */
        offset?: number;
        /** @description A search term. */
        search?: string;
      };
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaginatedWeeklyAvailabilityList'];
        };
      };
    };
  };
  v1_availability_parishes_list: {
    parameters: {
      query?: {
        city?: string;
        city__icontains?: string;
        is_active?: boolean;
        /** @description Number of results to return per page. */
        limit?: number;
        /** @description The initial index from which to return the results. */
        offset?: number;
        /** @description A search term. */
        search?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaginatedParishList'];
        };
      };
    };
  };
  v1_availability_parishes_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['Parish'];
        'multipart/form-data': components['schemas']['Parish'];
        'application/x-www-form-urlencoded': components['schemas']['Parish'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Parish'];
        };
      };
    };
  };
  v1_availability_parishes_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Parish'];
        };
      };
    };
  };
  v1_availability_parishes_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['Parish'];
        'multipart/form-data': components['schemas']['Parish'];
        'application/x-www-form-urlencoded': components['schemas']['Parish'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Parish'];
        };
      };
    };
  };
  v1_availability_parishes_destroy: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  v1_availability_parishes_partial_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['PatchedParish'];
        'multipart/form-data': components['schemas']['PatchedParish'];
        'application/x-www-form-urlencoded': components['schemas']['PatchedParish'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Parish'];
        };
      };
    };
  };
  v1_availability_services_list: {
    parameters: {
      query?: {
        /** @description Number of results to return per page. */
        limit?: number;
        /** @description The initial index from which to return the results. */
        offset?: number;
        /** @description A search term. */
        search?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaginatedServiceTypeList'];
        };
      };
    };
  };
  v1_availability_services_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ServiceType'];
        'multipart/form-data': components['schemas']['ServiceType'];
        'application/x-www-form-urlencoded': components['schemas']['ServiceType'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ServiceType'];
        };
      };
    };
  };
  v1_availability_services_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ServiceType'];
        };
      };
    };
  };
  v1_availability_services_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ServiceType'];
        'multipart/form-data': components['schemas']['ServiceType'];
        'application/x-www-form-urlencoded': components['schemas']['ServiceType'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ServiceType'];
        };
      };
    };
  };
  v1_availability_services_destroy: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  v1_availability_services_partial_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['PatchedServiceType'];
        'multipart/form-data': components['schemas']['PatchedServiceType'];
        'application/x-www-form-urlencoded': components['schemas']['PatchedServiceType'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ServiceType'];
        };
      };
    };
  };
  v1_bible_books_list: {
    parameters: {
      query?: {
        /** @description Number of results to return per page. */
        limit?: number;
        /** @description The initial index from which to return the results. */
        offset?: number;
        search?: string | null;
        testament?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BookMetadataOutput'][];
        };
      };
    };
  };
  v1_bible_books_chapters_verses_list: {
    parameters: {
      query?: {
        excerpt?: boolean;
        /** @description Number of results to return per page. */
        limit?: number;
        /** @description The initial index from which to return the results. */
        offset?: number;
        verses?: string | null;
      };
      header?: never;
      path: {
        book_id: number;
        chapter_number: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VerseOutput'][];
        };
      };
    };
  };
  v1_bible_search_list: {
    parameters: {
      query: {
        book_slug?: string | null;
        chapter_number?: number | null;
        hybrid?: boolean;
        limit?: number;
        q: string;
        testament?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SearchBookGroupOutput'][];
        };
      };
    };
  };
  v1_bible_testaments_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TestamentWithBooksOutput'][];
        };
      };
    };
  };
  v1_bible_testaments_books_list: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        testament_slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BookMetadataOutput'][];
        };
      };
    };
  };
  v1_errors_trigger_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  v1_errors_trigger_exception_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  v1_errors_trigger_unique_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  v1_files_upload_direct_finish_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  v1_files_upload_direct_local_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        file_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  v1_files_upload_direct_start_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  v1_files_upload_standard_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  v1_liturgy_date_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        date_str: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LiturgicalDate'];
        };
      };
    };
  };
  v1_liturgy_offices_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Office'];
        };
      };
    };
  };
  v1_liturgy_readings_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Reading'];
        };
      };
    };
  };
  v1_liturgy_today_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LiturgicalDate'];
        };
      };
    };
  };
  v1_rag_query_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RagQuery'];
        'multipart/form-data': components['schemas']['RagQuery'];
        'application/x-www-form-urlencoded': components['schemas']['RagQuery'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RagResponse'];
        };
      };
    };
  };
  v1_rosary_day_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        day: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TodayRosaryOutput'];
        };
      };
    };
  };
  v1_rosary_groups_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Group'][];
        };
      };
    };
  };
  v1_rosary_groups_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Group'];
        };
      };
    };
  };
  v1_rosary_mysteries_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Mystery'];
        };
      };
    };
  };
  v1_rosary_prayers_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Prayer'][];
        };
      };
    };
  };
  v1_rosary_search_list: {
    parameters: {
      query?: {
        /** @description Search query */
        q?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SearchPrayer'][];
        };
      };
    };
  };
  v1_rosary_today_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TodayRosaryOutput'];
        };
      };
    };
  };
  v1_rosary_vector_search_list: {
    parameters: {
      query?: {
        /** @description Semantic search query */
        q?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SearchPrayer'][];
        };
      };
    };
  };
  v1_users_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  v1_users_retrieve_2: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  v1_users_update_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  v1_users_create_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
